# main.py
SCREEN_SIZE = 600
FOOD_COLLISION_SIZE = 15
TAIL_COLLISION_SIZE = 10

# food.py
FOOD_SIZE = 0.5
NEGATIVE_BOUNDARY = -280
POSITIVE_BOUNDARY = 280

# scoreboard
SCOREBOARD_POSITION = 270
SCOREBOARD_ALIGNMENT = "center"
SCOREBOARD_FONT = ("Arial", 20, "normal")

# snake
STARTING_POSITIONS = [(0, 0), (-20, 0), (-40, 0)]
MOVE_DISTANCE = 20
MOVE_UP = 90
MOVE_DOWN = 270
MOVE_LEFT = 180
MOVE_RIGHT = 0
